---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1p-hello-service
spec:
  selector:
    matchLabels:
      app: s1p-hello-service
  replicas: 1
  template:
    metadata:
      labels:
        app: s1p-hello-service
    spec:
      containers:
      - name: s1p-hello-service
        image: msathepivotal/s1p-hello-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: s1p-hello-service
  labels:
    app: s1p-hello-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: s1p-hello-service
