---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1p-hello-service-baseline
  labels:
    app: s1p-hello-service
spec:
  selector:
    matchLabels:
      app: s1p-hello-service-baseline
  replicas: 1
  template:
    metadata:
      labels:
        app: s1p-hello-service-baseline
    spec:
      containers:
      - name: s1p-hello-service-baseline
        image: msathepivotal/s1p-hello-service:0.0.1-SNAPSHOT-20190928.135943Z.bd26e35
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ACA_STAGE
          value: "baseline"
        - name: GIT_SHA
          value: "bd26e35"
        - name: VERSION
          value: "0.0.1-SNAPSHOT-20190928.135943Z.bd26e35"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace