---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1p-hello-service
  labels:
    app: s1p-hello-service
spec:
  selector:
    matchLabels:
      app: s1p-hello-service
  replicas: 3
  template:
    metadata:
      labels:
        app: s1p-hello-service
    spec:
      containers:
      - name: s1p-hello-service
        image: msathepivotal/s1p-hello-service:0.0.1-SNAPSHOT-20191007.141443Z.8ab182f
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ACA_STAGE
          value: "prod"
        - name: GIT_SHA
          value: "8ab182f"
        - name: VERSION
          value: "0.0.1-SNAPSHOT-20191007.141443Z.8ab182f"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
