---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1p-hello-service-canary
  labels:
    app: s1p-hello-service
spec:
  selector:
    matchLabels:
      app: s1p-hello-service-canary
  replicas: 1
  template:
    metadata:
      labels:
        app: s1p-hello-service-canary
    spec:
      containers:
      - name: s1p-hello-service-canary
        image: msathepivotal/s1p-hello-service:0.0.1-SNAPSHOT-20190930.123014Z.09694ae
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ACA_STAGE
          value: "canary"
        - name: GIT_SHA
          value: "09694ae"
        - name: VERSION
          value: "0.0.1-SNAPSHOT-20190930.123014Z.09694ae"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace