---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1p-hello-service-baseline
  labels:
    app: s1p-hello-service
spec:
  selector:
    matchLabels:
      app: s1p-hello-service-baseline
  replicas: 1
  template:
    metadata:
      labels:
        app: s1p-hello-service-baseline
    spec:
      containers:
      - name: s1p-hello-service-baseline
        image: msathepivotal/s1p-hello-service:BASELINE-SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ACA_STAGE
          value: "baseline"
        - name: GIT_SHA
            value: "BASELINE-SHA"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace